"use strict";
exports.__esModule = true;
var direccion_1 = require("../CLASES/direccion");
var dni_1 = require("../CLASES/dni");
var mail_1 = require("../CLASES/mail");
var persona_1 = require("../CLASES/persona");
var sexo_1 = require("../CLASES/sexo");
var telefono_1 = require("../CLASES/telefono");
var personas = [];
var juan = new persona_1.Persona();
juan.setNombre("Juan");
juan.setApellidos("Domiguez Perez");
juan.setEdad(34);
juan.setDni(new dni_1.Dni(43567543, "Y"));
juan.setCumpleañOs(new Date("1988-04-12T21:21:21.212Z"));
juan.setColorFavorito("Rojo");
juan.setSexo(sexo_1.Sexo.hombre);
juan.getDirecciones().push(new direccion_1.Direccion("Calle San Antonio", 32, 2, "B", 8001, "Barcelona", "Barcelona"));
juan.getMails().push(new mail_1.Mail("personal", "juandominguezperez88@gmail.com"));
juan.getTelefonos().push(new telefono_1.Telefono("Particular", 656638555));
juan.getNotas().push("Tiene una enfermedad muy grave");
var periquito = new persona_1.Persona();
periquito.setNombre("Periquito");
periquito.setApellidos("Domiguez Perez");
periquito.setEdad(33);
periquito.setDni(new dni_1.Dni(86594256, "P"));
periquito.setCumpleañOs(new Date("1989-04-12T21:21:21.212Z"));
periquito.setColorFavorito("Azul");
periquito.setSexo(sexo_1.Sexo.hombre);
periquito.getDirecciones().push(new direccion_1.Direccion("Calle Tulipanes", 8, 21, "F", 8003, "Barcelona", "Barcelona"));
periquito.getMails().push(new mail_1.Mail("personal", "periquitodp89@gmail.com"));
periquito.getTelefonos().push(new telefono_1.Telefono("Particular", 789456123));
periquito.getNotas().push("Tiene 3 perritos");
var andres = new persona_1.Persona();
andres.setNombre("Andrés");
andres.setApellidos("Domiguez Perez");
andres.setEdad(32);
andres.setDni(new dni_1.Dni(25784635, "V"));
andres.setCumpleañOs(new Date("1990-04-12T21:21:21.212Z"));
andres.setColorFavorito("Naranja");
andres.setSexo(sexo_1.Sexo.hombre);
andres.getDirecciones().push(new direccion_1.Direccion("Calle Saturno", 2, 3, "D", 8005, "Barcelona", "Barcelona"));
andres.getMails().push(new mail_1.Mail("personal", "andres900412@gmail.com"));
andres.getTelefonos().push(new telefono_1.Telefono("Particular", 78585251));
andres.getNotas().push("El más joven de los hermanos Dominguez Perez");
personas.push(juan);
personas.push(periquito);
personas.push(andres);
console.log("Antes del cambio\n");
personas.forEach(function (persona) {
    console.log(persona.toString());
    console.log("\n");
});
console.log("Buscando a persona con DNI: %s", new dni_1.Dni(86594256, "P").toString());
var filtrado = personas.filter(function (persona) { return persona.getDni().equals(new dni_1.Dni(86594256, "P")); }).pop();
console.log("Encontrado:\n" + filtrado.toString() + "\n");
filtrado.getDirecciones().push(new direccion_1.Direccion("De la flor", 98, 76, "p", 52524, "Barcelona", "Barcelona"));
filtrado.getTelefonos().push(new telefono_1.Telefono("Particular", 678987868));
filtrado.getMails().push(new mail_1.Mail("personal", "periquitotoflama@gmail.com"));
personas.forEach;
console.log("Después del cambio\n");
personas.forEach(function (persona) {
    console.log(persona.toString());
    console.log("\n");
});
